import { fromEvent } from "rxjs";
import { map, tap } from 'rxjs/operators';

const text = document.createElement('div');
text.innerHTML = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor lobortis viverra. Vivamus tellus est, pulvinar sit amet malesuada eu, pulvinar fringilla nisl. Pellentesque consequat ex in ante tincidunt, ac mollis elit aliquet. Proin elit tortor, ullamcorper et varius sed, viverra ut velit. Donec lobortis orci eu elit tempus, et vulputate ipsum congue. Pellentesque placerat, enim et tristique consectetur, mauris diam vehicula lorem, ac feugiat diam dolor eget diam. In sed neque eu massa fringilla elementum. Cras rutrum enim at sem dictum, id sodales odio gravida. Praesent nec volutpat turpis, id tempus ex. Aenean vel congue elit, eu cursus elit. Mauris massa eros, ullamcorper eget rutrum vel, ullamcorper eget ipsum. Nulla iaculis felis in varius accumsan. Mauris egestas velit ac lectus feugiat posuere. Aenean non rhoncus erat. Ut sit amet turpis sed massa faucibus aliquet nec at eros. Ut pulvinar odio sit amet justo suscipit ullamcorper.
<br/><br/>
Fusce rutrum sollicitudin nulla, sed condimentum odio convallis non. Donec accumsan facilisis tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ut metus libero. Vivamus dignissim libero ac volutpat molestie. Cras quis congue nibh, quis tempor turpis. Nunc imperdiet leo ac ipsum suscipit, vel efficitur justo egestas. Sed ac lectus sapien. In congue tristique sem vel convallis.
<br/><br/>
In elementum porta imperdiet. Nullam viverra, ligula nec tincidunt congue, est velit pretium sem, nec dignissim sapien dui vel neque. Sed eget viverra ligula, ac mollis leo. Curabitur maximus quam nulla. Quisque pulvinar molestie risus. Quisque posuere at massa ut auctor. Donec massa elit, sollicitudin non ullamcorper eu, sagittis laoreet magna. Curabitur dui arcu, porta eget dolor ac, congue aliquam sem. Fusce iaculis sagittis lectus, et porttitor augue egestas ut. Sed fringilla viverra quam ut eleifend.
<br/><br/>
Nullam efficitur elementum lectus, in cursus lacus tincidunt at. Curabitur id erat vitae libero dictum facilisis. Praesent aliquam tempus accumsan. Curabitur posuere odio laoreet massa interdum ultricies. Etiam aliquet risus ac cursus elementum. Nulla lacinia blandit velit id dapibus. In at ullamcorper eros. Phasellus non bibendum felis, at ultrices nunc. Maecenas sem ipsum, aliquam eget ligula vel, lobortis molestie ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum erat sed ipsum tristique, placerat tempus purus scelerisque. Proin dapibus rhoncus imperdiet. Nunc id enim ut urna ornare pulvinar vel quis elit. Donec felis sapien, fermentum eget turpis in, consequat faucibus mauris.
<br/><br/>
Duis non urna pretium, elementum quam sit amet, venenatis nulla. Proin lectus mi, finibus a turpis quis, hendrerit facilisis nunc. Vestibulum placerat blandit tellus, quis scelerisque sem commodo id. Mauris pharetra odio eget sapien ornare rutrum. Morbi pulvinar enim at tellus lobortis, ac laoreet lorem luctus. Nunc pellentesque purus non erat ornare, nec volutpat eros pellentesque. Quisque condimentum facilisis aliquet. Phasellus quis orci diam. Phasellus ex dolor, dapibus non eros eget, porttitor molestie diam. Nam vestibulum et massa eget scelerisque. Ut quis nisl bibendum, porttitor odio sed, commodo enim. Phasellus blandit nisi sit amet dui consectetur, nec lobortis justo mattis. Maecenas dictum purus tristique, euismod nibh vitae, vehicula lectus. Duis accumsan orci metus, et iaculis orci congue nec. Morbi imperdiet augue ullamcorper enim laoreet eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor lobortis viverra. Vivamus tellus est, pulvinar sit amet malesuada eu, pulvinar fringilla nisl. Pellentesque consequat ex in ante tincidunt, ac mollis elit aliquet. Proin elit tortor, ullamcorper et varius sed, viverra ut velit. Donec lobortis orci eu elit tempus, et vulputate ipsum congue. Pellentesque placerat, enim et tristique consectetur, mauris diam vehicula lorem, ac feugiat diam dolor eget diam. In sed neque eu massa fringilla elementum. Cras rutrum enim at sem dictum, id sodales odio gravida. Praesent nec volutpat turpis, id tempus ex. Aenean vel congue elit, eu cursus elit. Mauris massa eros, ullamcorper eget rutrum vel, ullamcorper eget ipsum. Nulla iaculis felis in varius accumsan. Mauris egestas velit ac lectus feugiat posuere. Aenean non rhoncus erat. Ut sit amet turpis sed massa faucibus aliquet nec at eros. Ut pulvinar odio sit amet justo suscipit ullamcorper.
<br/><br/>
Fusce rutrum sollicitudin nulla, sed condimentum odio convallis non. Donec accumsan facilisis tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ut metus libero. Vivamus dignissim libero ac volutpat molestie. Cras quis congue nibh, quis tempor turpis. Nunc imperdiet leo ac ipsum suscipit, vel efficitur justo egestas. Sed ac lectus sapien. In congue tristique sem vel convallis.
<br/><br/>
In elementum porta imperdiet. Nullam viverra, ligula nec tincidunt congue, est velit pretium sem, nec dignissim sapien dui vel neque. Sed eget viverra ligula, ac mollis leo. Curabitur maximus quam nulla. Quisque pulvinar molestie risus. Quisque posuere at massa ut auctor. Donec massa elit, sollicitudin non ullamcorper eu, sagittis laoreet magna. Curabitur dui arcu, porta eget dolor ac, congue aliquam sem. Fusce iaculis sagittis lectus, et porttitor augue egestas ut. Sed fringilla viverra quam ut eleifend.
<br/><br/>
Nullam efficitur elementum lectus, in cursus lacus tincidunt at. Curabitur id erat vitae libero dictum facilisis. Praesent aliquam tempus accumsan. Curabitur posuere odio laoreet massa interdum ultricies. Etiam aliquet risus ac cursus elementum. Nulla lacinia blandit velit id dapibus. In at ullamcorper eros. Phasellus non bibendum felis, at ultrices nunc. Maecenas sem ipsum, aliquam eget ligula vel, lobortis molestie ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum erat sed ipsum tristique, placerat tempus purus scelerisque. Proin dapibus rhoncus imperdiet. Nunc id enim ut urna ornare pulvinar vel quis elit. Donec felis sapien, fermentum eget turpis in, consequat faucibus mauris.
<br/><br/>
Duis non urna pretium, elementum quam sit amet, venenatis nulla. Proin lectus mi, finibus a turpis quis, hendrerit facilisis nunc. Vestibulum placerat blandit tellus, quis scelerisque sem commodo id. Mauris pharetra odio eget sapien ornare rutrum. Morbi pulvinar enim at tellus lobortis, ac laoreet lorem luctus. Nunc pellentesque purus non erat ornare, nec volutpat eros pellentesque. Quisque condimentum facilisis aliquet. Phasellus quis orci diam. Phasellus ex dolor, dapibus non eros eget, porttitor molestie diam. Nam vestibulum et massa eget scelerisque. Ut quis nisl bibendum, porttitor odio sed, commodo enim. Phasellus blandit nisi sit amet dui consectetur, nec lobortis justo mattis. Maecenas dictum purus tristique, euismod nibh vitae, vehicula lectus. Duis accumsan orci metus, et iaculis orci congue nec. Morbi imperdiet augue ullamcorper enim laoreet eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor lobortis viverra. Vivamus tellus est, pulvinar sit amet malesuada eu, pulvinar fringilla nisl. Pellentesque consequat ex in ante tincidunt, ac mollis elit aliquet. Proin elit tortor, ullamcorper et varius sed, viverra ut velit. Donec lobortis orci eu elit tempus, et vulputate ipsum congue. Pellentesque placerat, enim et tristique consectetur, mauris diam vehicula lorem, ac feugiat diam dolor eget diam. In sed neque eu massa fringilla elementum. Cras rutrum enim at sem dictum, id sodales odio gravida. Praesent nec volutpat turpis, id tempus ex. Aenean vel congue elit, eu cursus elit. Mauris massa eros, ullamcorper eget rutrum vel, ullamcorper eget ipsum. Nulla iaculis felis in varius accumsan. Mauris egestas velit ac lectus feugiat posuere. Aenean non rhoncus erat. Ut sit amet turpis sed massa faucibus aliquet nec at eros. Ut pulvinar odio sit amet justo suscipit ullamcorper.
<br/><br/>
Fusce rutrum sollicitudin nulla, sed condimentum odio convallis non. Donec accumsan facilisis tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ut metus libero. Vivamus dignissim libero ac volutpat molestie. Cras quis congue nibh, quis tempor turpis. Nunc imperdiet leo ac ipsum suscipit, vel efficitur justo egestas. Sed ac lectus sapien. In congue tristique sem vel convallis.
<br/><br/>
In elementum porta imperdiet. Nullam viverra, ligula nec tincidunt congue, est velit pretium sem, nec dignissim sapien dui vel neque. Sed eget viverra ligula, ac mollis leo. Curabitur maximus quam nulla. Quisque pulvinar molestie risus. Quisque posuere at massa ut auctor. Donec massa elit, sollicitudin non ullamcorper eu, sagittis laoreet magna. Curabitur dui arcu, porta eget dolor ac, congue aliquam sem. Fusce iaculis sagittis lectus, et porttitor augue egestas ut. Sed fringilla viverra quam ut eleifend.
<br/><br/>
Nullam efficitur elementum lectus, in cursus lacus tincidunt at. Curabitur id erat vitae libero dictum facilisis. Praesent aliquam tempus accumsan. Curabitur posuere odio laoreet massa interdum ultricies. Etiam aliquet risus ac cursus elementum. Nulla lacinia blandit velit id dapibus. In at ullamcorper eros. Phasellus non bibendum felis, at ultrices nunc. Maecenas sem ipsum, aliquam eget ligula vel, lobortis molestie ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum erat sed ipsum tristique, placerat tempus purus scelerisque. Proin dapibus rhoncus imperdiet. Nunc id enim ut urna ornare pulvinar vel quis elit. Donec felis sapien, fermentum eget turpis in, consequat faucibus mauris.
<br/><br/>
Duis non urna pretium, elementum quam sit amet, venenatis nulla. Proin lectus mi, finibus a turpis quis, hendrerit facilisis nunc. Vestibulum placerat blandit tellus, quis scelerisque sem commodo id. Mauris pharetra odio eget sapien ornare rutrum. Morbi pulvinar enim at tellus lobortis, ac laoreet lorem luctus. Nunc pellentesque purus non erat ornare, nec volutpat eros pellentesque. Quisque condimentum facilisis aliquet. Phasellus quis orci diam. Phasellus ex dolor, dapibus non eros eget, porttitor molestie diam. Nam vestibulum et massa eget scelerisque. Ut quis nisl bibendum, porttitor odio sed, commodo enim. Phasellus blandit nisi sit amet dui consectetur, nec lobortis justo mattis. Maecenas dictum purus tristique, euismod nibh vitae, vehicula lectus. Duis accumsan orci metus, et iaculis orci congue nec. Morbi imperdiet augue ullamcorper enim laoreet eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor lobortis viverra. Vivamus tellus est, pulvinar sit amet malesuada eu, pulvinar fringilla nisl. Pellentesque consequat ex in ante tincidunt, ac mollis elit aliquet. Proin elit tortor, ullamcorper et varius sed, viverra ut velit. Donec lobortis orci eu elit tempus, et vulputate ipsum congue. Pellentesque placerat, enim et tristique consectetur, mauris diam vehicula lorem, ac feugiat diam dolor eget diam. In sed neque eu massa fringilla elementum. Cras rutrum enim at sem dictum, id sodales odio gravida. Praesent nec volutpat turpis, id tempus ex. Aenean vel congue elit, eu cursus elit. Mauris massa eros, ullamcorper eget rutrum vel, ullamcorper eget ipsum. Nulla iaculis felis in varius accumsan. Mauris egestas velit ac lectus feugiat posuere. Aenean non rhoncus erat. Ut sit amet turpis sed massa faucibus aliquet nec at eros. Ut pulvinar odio sit amet justo suscipit ullamcorper.
<br/><br/>
Fusce rutrum sollicitudin nulla, sed condimentum odio convallis non. Donec accumsan facilisis tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ut metus libero. Vivamus dignissim libero ac volutpat molestie. Cras quis congue nibh, quis tempor turpis. Nunc imperdiet leo ac ipsum suscipit, vel efficitur justo egestas. Sed ac lectus sapien. In congue tristique sem vel convallis.
<br/><br/>
In elementum porta imperdiet. Nullam viverra, ligula nec tincidunt congue, est velit pretium sem, nec dignissim sapien dui vel neque. Sed eget viverra ligula, ac mollis leo. Curabitur maximus quam nulla. Quisque pulvinar molestie risus. Quisque posuere at massa ut auctor. Donec massa elit, sollicitudin non ullamcorper eu, sagittis laoreet magna. Curabitur dui arcu, porta eget dolor ac, congue aliquam sem. Fusce iaculis sagittis lectus, et porttitor augue egestas ut. Sed fringilla viverra quam ut eleifend.
<br/><br/>
Nullam efficitur elementum lectus, in cursus lacus tincidunt at. Curabitur id erat vitae libero dictum facilisis. Praesent aliquam tempus accumsan. Curabitur posuere odio laoreet massa interdum ultricies. Etiam aliquet risus ac cursus elementum. Nulla lacinia blandit velit id dapibus. In at ullamcorper eros. Phasellus non bibendum felis, at ultrices nunc. Maecenas sem ipsum, aliquam eget ligula vel, lobortis molestie ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum erat sed ipsum tristique, placerat tempus purus scelerisque. Proin dapibus rhoncus imperdiet. Nunc id enim ut urna ornare pulvinar vel quis elit. Donec felis sapien, fermentum eget turpis in, consequat faucibus mauris.
<br/><br/>
Duis non urna pretium, elementum quam sit amet, venenatis nulla. Proin lectus mi, finibus a turpis quis, hendrerit facilisis nunc. Vestibulum placerat blandit tellus, quis scelerisque sem commodo id. Mauris pharetra odio eget sapien ornare rutrum. Morbi pulvinar enim at tellus lobortis, ac laoreet lorem luctus. Nunc pellentesque purus non erat ornare, nec volutpat eros pellentesque. Quisque condimentum facilisis aliquet. Phasellus quis orci diam. Phasellus ex dolor, dapibus non eros eget, porttitor molestie diam. Nam vestibulum et massa eget scelerisque. Ut quis nisl bibendum, porttitor odio sed, commodo enim. Phasellus blandit nisi sit amet dui consectetur, nec lobortis justo mattis. Maecenas dictum purus tristique, euismod nibh vitae, vehicula lectus. Duis accumsan orci metus, et iaculis orci congue nec. Morbi imperdiet augue ullamcorper enim laoreet eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor lobortis viverra. Vivamus tellus est, pulvinar sit amet malesuada eu, pulvinar fringilla nisl. Pellentesque consequat ex in ante tincidunt, ac mollis elit aliquet. Proin elit tortor, ullamcorper et varius sed, viverra ut velit. Donec lobortis orci eu elit tempus, et vulputate ipsum congue. Pellentesque placerat, enim et tristique consectetur, mauris diam vehicula lorem, ac feugiat diam dolor eget diam. In sed neque eu massa fringilla elementum. Cras rutrum enim at sem dictum, id sodales odio gravida. Praesent nec volutpat turpis, id tempus ex. Aenean vel congue elit, eu cursus elit. Mauris massa eros, ullamcorper eget rutrum vel, ullamcorper eget ipsum. Nulla iaculis felis in varius accumsan. Mauris egestas velit ac lectus feugiat posuere. Aenean non rhoncus erat. Ut sit amet turpis sed massa faucibus aliquet nec at eros. Ut pulvinar odio sit amet justo suscipit ullamcorper.
<br/><br/>
Fusce rutrum sollicitudin nulla, sed condimentum odio convallis non. Donec accumsan facilisis tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse ut metus libero. Vivamus dignissim libero ac volutpat molestie. Cras quis congue nibh, quis tempor turpis. Nunc imperdiet leo ac ipsum suscipit, vel efficitur justo egestas. Sed ac lectus sapien. In congue tristique sem vel convallis.
<br/><br/>
In elementum porta imperdiet. Nullam viverra, ligula nec tincidunt congue, est velit pretium sem, nec dignissim sapien dui vel neque. Sed eget viverra ligula, ac mollis leo. Curabitur maximus quam nulla. Quisque pulvinar molestie risus. Quisque posuere at massa ut auctor. Donec massa elit, sollicitudin non ullamcorper eu, sagittis laoreet magna. Curabitur dui arcu, porta eget dolor ac, congue aliquam sem. Fusce iaculis sagittis lectus, et porttitor augue egestas ut. Sed fringilla viverra quam ut eleifend.
<br/><br/>
Nullam efficitur elementum lectus, in cursus lacus tincidunt at. Curabitur id erat vitae libero dictum facilisis. Praesent aliquam tempus accumsan. Curabitur posuere odio laoreet massa interdum ultricies. Etiam aliquet risus ac cursus elementum. Nulla lacinia blandit velit id dapibus. In at ullamcorper eros. Phasellus non bibendum felis, at ultrices nunc. Maecenas sem ipsum, aliquam eget ligula vel, lobortis molestie ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam rutrum erat sed ipsum tristique, placerat tempus purus scelerisque. Proin dapibus rhoncus imperdiet. Nunc id enim ut urna ornare pulvinar vel quis elit. Donec felis sapien, fermentum eget turpis in, consequat faucibus mauris.
<br/><br/>
Duis non urna pretium, elementum quam sit amet, venenatis nulla. Proin lectus mi, finibus a turpis quis, hendrerit facilisis nunc. Vestibulum placerat blandit tellus, quis scelerisque sem commodo id. Mauris pharetra odio eget sapien ornare rutrum. Morbi pulvinar enim at tellus lobortis, ac laoreet lorem luctus. Nunc pellentesque purus non erat ornare, nec volutpat eros pellentesque. Quisque condimentum facilisis aliquet. Phasellus quis orci diam. Phasellus ex dolor, dapibus non eros eget, porttitor molestie diam. Nam vestibulum et massa eget scelerisque. Ut quis nisl bibendum, porttitor odio sed, commodo enim. Phasellus blandit nisi sit amet dui consectetur, nec lobortis justo mattis. Maecenas dictum purus tristique, euismod nibh vitae, vehicula lectus. Duis accumsan orci metus, et iaculis orci congue nec. Morbi imperdiet augue ullamcorper enim laoreet eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
`;

const body = document.querySelector('body');
body.append(text);

const progressBar = document.createElement('div');
progressBar.setAttribute('class', 'progress-bar');
body.append(progressBar);

const getScrollValue = (event) => {
    const { scrollTop, scrollHeight, clientHeight } = event.target.documentElement;
    // console.log({ scrollTop, scrollHeight, clientHeight });
    return Math.round(scrollTop / (scrollHeight - clientHeight) * 100);
}

// Streams
const scroll$ = fromEvent(document, 'scroll');
// scroll$.subscribe(console.log);

const progress$ = scroll$.pipe(
    map(getScrollValue),
    tap(console.log)
);

progress$.subscribe(value => {
    progressBar.style.width = `${value}%`;
});